### ISSUE TITLE
PyPI package mess

### ISSUE THREAD

**Issue by zgoda-mobica** [google/python-adb#108]
There are at least 4 packages on PyPI that provide python-adb under different names - `adb`, `python-adb`, `ak-adb`, `frida-android-adb`, none of which contains current code as found in this repository. May I ask for official release?

**Comment by fahhem** [comment]
Wow, I didn't know there were so many PyPI releases. Not sure if I can get the other 3 down, but `adb` is the official release and I've uploaded a 1.3.0 release. Thanks for the kick I needed!
