### ISSUE TITLE
LIBUSB_ERROR_OVERFLOW when running in thread

### ISSUE THREAD

**Issue by zgoda** [google/python-adb#114]
I'm trying to run ADB command in thread (specifically, using Twisted `deferToThread()`) but everytime the returning result is longer than just handful of lines, such as from `Shell('getprop')`, I get `ReadFailedError` with this description on subsequent command:

```
ERROR - [Failure instance: Traceback: <class 'adb.usb_exceptions.ReadFailedError'>: Could not receive data from ddeec0a1 (timeout 10000ms): LIBUSB_ERROR_OVERFLOW [-8]
```

The `AdbCommands` object is created in reactor (main) thread and later is passed to threaded execution. Subsequent commands are executed sequentially.

Am I doing something illegal/stupid/wrong here?

**Comment by zgoda** [comment]
Okay, PEBKAC. Found a bug in my own code, sorry for the noise.

**Comment by ashwinipatankar** [comment]
And what was the bug ? I am also facing the same issue while suing Install

**Comment by zgoda** [comment]
@ashwinipatankar I'm sorry, I can't recall. Something related to Twisted and deferreds.
