### ISSUE TITLE
Why did not rewrite ID device ? 

### ISSUE THREAD

**Issue by vBlackOut** [google/python-adb#132]
hello, i find the broken code 

https://github.com/google/python-adb/blob/master/adb/adb_protocol.py#L133

what did you just write 
self.remote_id = remote_id

for rewrite bad remote_id you stop the process it's not nessesary.

thank you

**Comment by fahhem** [comment]
That is not correct. If the `remote_id` changes, it's because someone else (or another python-adb process) is talking to the same device, and we don't support parallel communications at the moment.
