### ISSUE TITLE
Push: NoneType has no attribute Write

### ISSUE THREAD

**Issue by penn5** [google/python-adb#134]
I am getting the error: 
```
b'device'
Traceback (most recent call last):
  File "autoroot.py", line 123, in <module>
    install_firmware(dloadfirmware, device)
  File "autoroot.py", line 120, in install_firmware
    print(device.Push(os.path.join(d, 'Software', 'dload'), storage+'/dload', timeout_ms=100000))
  File "/home/penn/python-adb/adb/adb_commands.py", line 269, in Push
    progress_callback=progress_callback)
  File "/home/penn/python-adb/adb/adb_commands.py", line 280, in Push
    mtime=int(mtime), progress_callback=progress_callback, **kwargs)
  File "/home/penn/python-adb/adb/filesync_protocol.py", line 149, in Push
    cnxn.Send(b'DATA', data)
  File "/home/penn/python-adb/adb/filesync_protocol.py", line 207, in Send
    self._Flush()
  File "/home/penn/python-adb/adb/filesync_protocol.py", line 254, in _Flush
    self.adb.Write(self.send_buffer[:self.send_idx])
AttributeError: 'NoneType' object has no attribute 'Write'
```

I've confirmed that the path I'm pushing to exists. I'm pushing a directory to another directory. I'm using Ubuntu 18.04. I am able to use the Shell command fine.

This looks similar to #125 except in Push not Pull.

The adbd is running as root on the phone, as is python3 on my PC.

**Comment by vBlackOut** [comment]
Hello, what is your version Android me it's 8.1

**Comment by vBlackOut** [comment]
For me solve temporary Look here for me solve my problem temporary https://github.com/google/python-adb/issues/132

**Comment by vBlackOut** [comment]
Sorry bad comment :/ sorry

**Comment by vBlackOut** [comment]
It's just ré-identify the id if change

**Comment by vBlackOut** [comment]
Not best practice but it's works

**Comment by vBlackOut** [comment]
Sorry I use GitHub on phone (fasthub) it's not ideal for comment and explore the interface GUI

**Comment by caffeinatedMike** [comment]
I use the same app and have zero issues with comments, etc. Also, your explanation still makes zero sense "It's just re-identify the I'd if change" isn't even a proper sentence. And even after being told by the main contributor of the repo that that is not a fix you continue to spam peoples' posts with this. Just PLEASE STOP. Listen to his comment and stop suggesting this crudely thought-up bandaid of a "fix".

**Comment by vBlackOut** [comment]
It's just forward fix but it's not finally real fix

**Comment by vBlackOut** [comment]
I just for understand the code

**Comment by fahhem** [comment]
Whoa let's all calm down please. @vBlackOut is just trying to help (and clearly english isn't his first language, so give him a break), it seems you're a little too caffeinated here :)

Let's start over in a new issue to avoid this exchange.
