### ISSUE TITLE
Dead library, avoid !! - Out of date package, frustrating setup, lib is broken

### ISSUE THREAD

**Issue by chrisdepas** [google/python-adb#166]
My experience went something like this:

1. Install dependencies, copy example code and run
```diff
-ImportError: cannot import name 'sign_cryptography'
```
2. Go through recent commit history, change syntax to match older crypto lib
```diff
-ModuleNotFoundError: No module named 'M2Crypto'
```
3. Attempt to install M2Crypto
```diff
-Fails, because I need the dependencies
```
4. `~$ sudo apt install python3-dev libssl-dev build-essential swig`
5. `~$ pip3 install M2Crypto`

Okay, at this point I thought I could finally use the library, but it seems to be completely broken:

1. First, attempting to connect by providing a serial 

```diff
-Traceback (most recent call last):
-  File "main.py", line 29, in <module>
-    device.connect(serial)
-  File "main.py", line 15, in connect
-    self.device.ConnectDevice(rsa_keys=self.keys, serial=deviceSerial)
-  File "/home/chris/.local/lib/python3.6/site-packages/adb/adb_commands.py", line 130, in ConnectDevice
-    elif serial and b':' in serial:
-TypeError: argument of type 'UsbHandle' is not iterable
```
2. Remove the serial argument
```diff
-Traceback (most recent call last):
-  File "main.py", line 30, in <module>
-    device.connect(serial)
-  File "main.py", line 17, in connect
-    self.device.ConnectDevice(rsa_keys=self.keys)
-  File "/home/chris/.local/lib/python3.6/site-packages/adb/adb_commands.py", line 135, in ConnectDevice
-    timeout_ms=default_timeout_ms)
-  File "/home/chris/.local/lib/python3.6/site-packages/adb/common.py", line 221, in FindAndOpen
-    dev.Open()
-  File "/home/chris/.local/lib/python3.6/site-packages/adb/common.py", line 128, in Open
-    handle.claimInterface(iface_number)
-  File "/home/chris/.local/lib/python3.6/site-packages/usb1/__init__.py", line 1309, in claimInterface
-    libusb1.libusb_claim_interface(self.__handle, interface),
-  File "/home/chris/.local/lib/python3.6/site-packages/usb1/__init__.py", line 133, in mayRaiseUSBError
-    __raiseUSBError(value)
-  File "/home/chris/.local/lib/python3.6/site-packages/usb1/__init__.py", line 125, in raiseUSBError
-    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
- usb1.USBErrorBusy: LIBUSB_ERROR_BUSY [-6]
```

Although the 2nd issue might not be a problem with the library, it should be noted that the standard `adb` binary provided with android has no issues at all.

How is this such a mess? How is it that the biggest tech company in the world manages to provide an abysmal developer experience without fail? I understand that Google might not be able to keep every library up to date etc, but at least post a '__this is no longer being maintained__' message (which takes max 30 seconds) so I don't waste my entire afternoon

Just curious, a [breaking change](https://github.com/google/python-adb/commit/4b555e64d1e49d91ed851c59bb11b734b302f71d) (with the documentation) was merged which swapped out M2Crypto for py-cryptography. M2Crypto is still updated regularly, is there any reasoning behind this?

**Comment by fahhem** [comment]
Hey :)

This isn't an official Google repo, I'm an ex-Google eng and I legitimately forgot about this repo, sorry.

I'll try to look through PRs and merge them in. I'd be happy to accept more PRs in the coming weeks to get this back off the ground and ready for a 1.3 PyPI release.
