### ISSUE TITLE
can we get a new realease?

### ISSUE THREAD

**Issue by greyltc** [google/python-adb#168]
The instructions in the readme no longer work with the latest release.

**Comment by JeffLIrion** [comment]
You could do

```
pip install adb-homeassistant
```

which will install [this version from my fork](https://github.com/JeffLIrion/python-adb/tree/adb-homeassistant). It contains some commits and bug fixes that are not in the pypi-released version of this package. 

Or, if you only need ADB shell functionality over TCP (not USB), I would encourage you to use

```
pip install adb-shell
```

That's a stripped-down and simplified version of this package, and I'm trying to fix some bugs (mainly support for newer devices) and hopefully get some contributions from the community. See https://github.com/google/python-adb/issues/167 for more info.

**Comment by greyltc** [comment]
Are you saying the project here is dead?

**Comment by JeffLIrion** [comment]
> Are you saying the project here is dead?

It's not my place to say. 

But I will say that my `adb-shell` package is thoroughly documented, well-covered by unit tests, and if you submit a pull request then I will review it and (if warranted) create a new release on Pypi.

**Comment by fahhem** [comment]
Hey :)

This isn't an official Google repo, I'm an ex-Google eng and I legitimately forgot about this repo, sorry.

I'll try to look through PRs and merge them in. I'd be happy to accept more PRs in the coming weeks to get this back off the ground and ready for a 1.3 PyPI release.
