### ISSUE TITLE
Documentation or examples

### ISSUE THREAD

**Issue by serhatbolsu** [google/python-adb#29]
Hello, 

Can you provide more documentation about usage , also that link for Pycon 2016 is not working (asking permission), maybe you might at least fix that

**Comment by fahhem** [comment]
Thanks for pointing this out, turns out I couldn't share it from where it was so I copied it over and now you should be able to view it. Let me know if you can't.

Documentation is a bit sparse, sorry. I'd be happy to help if you said what you needed to do?
