### ISSUE TITLE
Instrumentation error results in exit code 0

### ISSUE THREAD

**Issue by bootstraponline** [google/python-adb#31]
<img width="433" alt="inst_fail_python_adb" src="https://cloud.githubusercontent.com/assets/1173057/20064463/d8571d52-a4d8-11e6-9c04-28f0609704fe.png">

I was hoping python-adb had correct exit codes on instrumentation failures.

**Comment by fahhem** [comment]
What command did you run for that? I don't see instrumentation_code in the codebase

**Comment by bootstraponline** [comment]
> python adb.zip shell am instrument -w -r -e package com.instructure.parentapp -e debug false com.instructure.parentapp.test/com.instructure.espresso.InstructureRunner

**Comment by fahhem** [comment]
Ah, this is a problem with the adb protocol that we cannot fix. adb shell doesn't provide the return code at all, only the stdout/stderr. If you want the return code, you'll have to add `; echo $?` at the end of your commands and parse that out. I can't do that automatically as it could cause problems with certain commandlines or else I would. :/

**Comment by bootstraponline** [comment]
Cool. Thanks for the info. I ended up capturing the command output and looking for the `FAILURES!!!` string.

**Comment by darran-kelinske-fivestars** [comment]
I know this is an old question, but how did you gather the test results when running tests like this?
