### ISSUE TITLE
Error when running demo code

### ISSUE THREAD

**Issue by paulzin** [google/python-adb#40]
`python-adb/adb/adb_protocol.py", line 187, in CalculateChecksum
    return sum(map(ord, data)) & 0xFFFFFFFF
TypeError: ord() expected string of length 1, but int found
`

**Comment by kronenpj** [comment]
This is related to issue #36.

**Comment by fahhem** [comment]
Sorry about the delay on this project, I haven't had a system with an ADB device I could use this all with in a while. I've just pushed a commit to fix this problem in particular.
