### ISSUE TITLE
ImportError: No module named 'cStringIO'

### ISSUE THREAD

**Issue by carltonwin8** [google/python-adb#43]
File "adb.zip/adb/common_cli.py", line 23, in <module>

Error seen when running with python 3.5.2 'python adb.zip devices' after clone and make_tools.py.

Apparently since python 3.0:
"The StringIO and cStringIO modules are gone." ... "use io.StringIO or io.BytesIO"
from https://docs.python.org/3.0/whatsnew/3.0.html

**Comment by phhusson** [comment]
Yes, https://github.com/google/python-adb/commit/a9ea7b4118ab8fbf2e8c6a48a22b7586978c358f only fixed the library-part of the project, not the executable part.
