### ISSUE TITLE
How to write a SQL update command with root privilege

### ISSUE THREAD

**Issue by henryhoang92** [google/python-adb#50]
```
1. adb shell

2. su -c 'sqlite3 /data/data/com.android.providers.settings/databases/settings.db "update system set value=5000 where name='screen_off_timeout'"'
```
But I am getting the following error:

Error: no such column: screen_off_timeout

 how to fix it?

**Comment by fahhem** [comment]
you need to escape the quotes around screen_off_timeout.

**Comment by henryhoang92** [comment]
what's escape the quotes here ? can you correct it for me?

**Comment by fahhem** [comment]
Escape: \\'

**Comment by henryhoang92** [comment]
```
def query_update(u, email, password):
    sql_exc = " su -c 'sqlite3 ./data/setting.db \"update system set name=\'"+email+"\' \"'"
    print(sql_exc)
    return u.adb_shell(sql_exc)
```
I added Escape: \' but It's not working

**Comment by fahhem** [comment]
That's a totally different query. This repository is for Python ADB, not other ADB problems. StackOverflow and other places are better suited to your queries

**Comment by henryhoang92** [comment]
I updated
```
```
def query_update(u, email, password):
    sql_exc = " su -c 'sqlite3 ./data/setting.db \"update system set name=\'"+email+"\' \"'"
    print(sql_exc)
    return u.Shell(sql_exc)
```
I added Escape: \' but It's not working
Error: no such colum
```

**Comment by henryhoang92** [comment]
Hi @fahhem  Same issue with your lib

**Comment by henryhoang92** [comment]
Hi @fahhem what solution for this issues?

**Comment by fahhem** [comment]
I don't think this is specific to this library. Are you able to do this using android's ADB and not this one?

**Comment by fahhem** [comment]
If this was a problem with this library, I'd be happy to help, but you're having this problem in general. Please use StackOverflow or similar to solve such questions
