### ISSUE TITLE
Protocol: AttributeError: 'NoneType' object has no attribute 'ReadUntilClose'

### ISSUE THREAD

**Issue by eismog** [google/python-adb#59]
Hi, 

I will get an error, when I run two error command:

Like this:
```python
import os.path as op

from adb import adb_commands
from adb import sign_m2crypto


# KitKat+ devices require authentication
signer = sign_m2crypto.M2CryptoSigner(
    op.expanduser('~/.android/adbkey'))
# Connect to the device
device = adb_commands.AdbCommands.ConnectDevice(
    rsa_keys=[signer])
# Now we can use Shell, Pull, Push, etc!
# for i in xrange(10):
#   print device.Shell('echo %d' % i)

print device.Shell('ls 333')
print device.Shell('ls 222')
print device.Shell('ls 111')
device.Close()
```

result:
```python
/usr/bin/python2.7 /home/ligf/PycharmProjects/test-adb/tmp.py
ls: 333: No such file or directory
Traceback (most recent call last):

  File "/home/ligf/PycharmProjects/test-adb/tmp.py", line 18, in <module>
    print device.Shell('ls 222')
  File "build/bdist.linux-x86_64/egg/adb/adb_commands.py", line 227, in Shell
  File "build/bdist.linux-x86_64/egg/adb/adb_protocol.py", line 377, in Command
  File "build/bdist.linux-x86_64/egg/adb/adb_protocol.py", line 405, in StreamingCommand
AttributeError: 'NoneType' object has no attribute 'ReadUntilClose'

Process finished with exit code 1
```

It may be a bug at here:
adb_protocol.py
```python
    if cmd == b'CLSE':
      # Device doesn't support this service.
      return None
    if cmd != b'OKAY':
      raise InvalidCommandError('Expected a ready response, got %s' % cmd,
                                cmd, (remote_id, their_local_id))
    return _AdbConnection(usb, local_id, remote_id, timeout_ms)
```

BRs
/Eismog

**Comment by myrfy001** [comment]
The same problem. Has it been solved?

My phone is Huawei Honor 8.

**Comment by fahhem** [comment]
Can you add this between line 253 and 254 of `adb/adb_protocol.py`: `print command`

Then run it again and paste the output here, please. This should only be happening if the device is either sending two `CLSE` responses or the library isn't handling the first `CLSE` in time.

**Comment by myrfy001** [comment]
Hi
the print output is here. The number `0` is the output of the first loop, the item in buckets are the output of `print(command, arg0, arg1, bytes(data))`

```
('AUTH', 1, 0, '\r\xbf_\xa5]\xbdUi\xbc\x02\x10n\x8f\xe2\xf9p\x17I:Y')
('CNXN', 16777216, 4096, 'device::ro.product.name=FRD-AL00;ro.product.model=FRD-AL00;ro.product.device=HWFRD;features=cmd,shell_v2')
('OKAY', 8, 1, '')
('WRTE', 8, 1, '0\n')
('CLSE', 8, 1, '')
0

('CLSE', 8, 1, '')
Traceback (most recent call last):
  File "test.py", line 24, in <module>
    print device.Shell('echo %d' % i)
  File "build/bdist.macosx-10.12-x86_64/egg/adb/adb_commands.py", line 227, in Shell
  File "build/bdist.macosx-10.12-x86_64/egg/adb/adb_protocol.py", line 386, in Command
  File "build/bdist.macosx-10.12-x86_64/egg/adb/adb_protocol.py", line 414, in StreamingCommand
AttributeError: 'NoneType' object has no attribute 'ReadUntilClose'
```

**Comment by MohammadAG** [comment]
This also seems to be a problem on an LG G6

Here's the output of print:
CNXN
OKAY
WRTE
CLSE
Traceback (most recent call last):
  File "/Users/mabugarbeyyeh/PycharmProjects/SEI_Client_Installer/installer.py", line 129, in <module>
    device.Shell("echo 2")
  File "build/bdist.macosx-10.13-intel/egg/adb/adb_commands.py", line 233, in Shell
  File "build/bdist.macosx-10.13-intel/egg/adb/adb_protocol.py", line 383, in Command
  File "build/bdist.macosx-10.13-intel/egg/adb/adb_protocol.py", line 411, in StreamingCommand
AttributeError: 'NoneType' object has no attribute 'ReadUntilClose'
CLSE

**Comment by alxhoff** [comment]
I am still affected by this issue

> File "/usr/lib/python2.7/site-packages/adb/adb_commands.py", line 366, in Shell
>     timeout_ms=timeout_ms)
>   File "/usr/lib/python2.7/site-packages/adb/adb_protocol.py", line 406, in Command
>     return ''.join(cls.StreamingCommand(usb, service, command, timeout_ms))
>   File "/usr/lib/python2.7/site-packages/adb/adb_protocol.py", line 434, in StreamingCommand
>     for data in connection.ReadUntilClose():
> AttributeError: 'NoneType' object has no attribute 'ReadUntilClose'

And my adb_protocol.py already contained

```
    if cmd == b'CLSE':
      # Some devices send two CLSEs
      cmd, remote_id, their_local_id, _ = cls.Read(usb, [b'CLSE', b'OKAY'],
                                                   timeout_ms=timeout_ms)
      # Device doesn't support this service.
      if cmd == b'CLSE':
        return None
```

Any help would be greatly appreciated as it seems to fail randomly and during periods of high ADB traffic.

**Comment by alxhoff** [comment]
Bump. This is plaguing my app like nothing else.

**Comment by alxhoff** [comment]
After having a fresh google around PR #151 seems to of fixed it up.

**Comment by embray** [comment]
@alxhoff Thanks for the confirmation.  If Google loves open source so much it'd be great if they gave developers of their open-source projects the time necessary to review and merge bug fixes to them 😀 😀 😀 
For myself I'll probably be forced to distribute my own fork of this package.
