### ISSUE TITLE
Running on top of Android emulator

### ISSUE THREAD

**Issue by ChapiIL** [google/python-adb#94]
Is it possible to run the lib on top of an Android emulator?
I'm using Memu and I'm able to run adb commands on it from command line.
Thanks.

**Comment by fahhem** [comment]
It depends, can you kill the adb server without it coming back right away? `adb kill-server`

See #98 for how to connect to an emulator using TCP

**Comment by fahhem** [comment]
From another issue, it looks like the emulator requires android's adb server to be up, so we can't take over the communication to the emulator.

The upside is that the emulator should have 0 packet drops, which cause the majority of the problems with using the android adb server.
