### ISSUE TITLE
./abootool 运行时候报错

### ISSUE THREAD

**Issue by Vxer-Lee** [google/python-adb#96]
错误提示: 
  return adb_commands.AdbCommands.ConnectDevice(self.usbdev,rsa_keys=[signer])
TypeError: unbound method ConnectDevice() must be called with AdbCommands instance as first argument (got UsbHandle instance instead)

**Comment by fahhem** [comment]
I don't know what abootool is, but it's using the old API. Update it to be
```py
adb = adb_commands.AdbCommands()
adb.ConnectDevice(...)
```
